#define FUNCTIONS_H

void numberfun();
void easiest();
void humancannonball2();
void symmetricorder();
void thelastproblem();
void tornbygge();
void fiftyshades();
void jobexpenses();
void nodup();
void grading();
void ladder();
int starbattles1();
void simplicity();
void simon();
void triangle();
void santaklas();
int sanic();
int rhyming();
int goodmorning();
int sretan();
int thanos();
int variablenames();